# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cassetie-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cassetie-iOS
  pod 'ReactorKit'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Then'
  pod 'SnapKit'
end
